Fix: Ledger device minimum migratable amount
iotaledger/legacy-migration-tool pull request #71
Opened 2023-12-01 12:15 UTC by brancoder

## Summary
Please summarize your changes, describing __what__ they are and __why__ they were made.
Resolves #69 

### Changelog
```
Please write an accurate and concise changelog for your changes.
```

## Relevant Issues
Please list any related issues (e.g. bug, task).

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [ ] Windows

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2023-12-05 14:34 UTC, begonaalvarezd requested changes

2023-12-05 14:34 UTC, begonaalvarezd commented on packages/shared/locales/en.json
> +                "inputWarning": "Amount displayed on ledger:"
ideally the amount should be included in the locale so translations are more accurate, there might be a case where the amount is in the middle of the sentence or something
```suggestion
                "inputWarning": "Amount displayed on ledger: {amount}"
```

2023-12-05 14:34 UTC, begonaalvarezd commented on packages/shared/locales/en.json
> +                "warning": "The transaction information displayed on your Ledger device won't match the information displayed below. The amounts displayed on the leger will differ as a result of mini
I would not make what shows ledger different from that we display in the transaction, we need to make a 100% exact match, but I would do it the other way around, explain that this is not the migratable amount, that less will be migrated but that we can have to crreate the tx with a min of 1 IOTA

2023-12-07 12:11 UTC, cpl121 approved these changes
Works for me, NJ @brancoder 🚀 
![Captura de pantalla de 2023-12-07 13-04-52](https://github.com/iotaledger/legacy-migration-tool/assets/100352899/7c903c26-1e93-4db8-a278-5d77ab6a4866)
![Captura de pantalla de 2023-12-07 13-07-56](https://github.com/iotaledger/legacy-migration-tool/assets/100352899/ee5d5d1f-2db8-442a-aa89-1edcac480a32)

2023-12-09 11:47 UTC, begonaalvarezd approved these changes

2023-12-09 11:47 UTC, merged